Sub Main

/declare c int local
/for c 1 to ${SpawnCount[pccorpse radius 100]}
	/target id ${NearestSpawn[${c},pccorpse radius 100].ID}
	/delay 3
    /say #cast 994


/next c


/return


Sub Type(InStr)
  /declare char string local
  /declare loopctr int local
  /for loopctr 1 to ${InStr.Length}
  /varset char ${InStr.Mid[${loopctr},1]}
  /if (!${char.Length}) {
    /nomodkey /keypress space chat
  } else {
    /nomodkey /keypress ${char} chat
  }
  /next loopctr
/return